#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer for web-01 and web-02
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 6516-web-01 3.235.60.205:80 check\n\tserver 6516-web-02 44.192.74.250:80 check" >> sudo tee-a /etc/haproxy/haproxy.cfg
sudo service haproxy start
